name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[🐛 Bug]: "
labels: [ "bug" ]
assignees: [ ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug clearly and what you expected to happen.
      placeholder: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: debug_logs
    attributes:
      label: Debug Logs
      description: Paste any relevant logs or error output here.
      render: shell
      placeholder: |
        Traceback (most recent call last):
        ...
    validations:
      required: false

  - type: input
    id: project_version
    attributes:
      label: Project Version
      description: Version of the project you are using.
      placeholder: e.g. v1.2.3
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: e.g. Python 3.11.7
    validations:
      required: true
