package io.github.dug22.lockspot.cipheralgorithms;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CiphertextGeneration {

    private final static Map<String, AbstractCipher> cipherAlgorithsMap = CipherRegistry.getCipherAlgorithmsMap();

    public static void main(String[] args) {
        Map<String, String> ciphertextSamples = new HashMap<>();
        List<String> sentences = List.of(
                "THE QUICK BROWN FOX JUMPS OVER 13 LAZY DOGS WHILE 42 BIRDS FLY ABOVE AND 7 CATS WATCH CAREFULLY AS 99 CLOUDS FORM SHAPES IN THE SKY DURING A BRIGHT SUNNY DAY FULL OF FUN AND ENERGY",
                "IN A VAST 2026 CITY FILLED WITH 50 SKYSCRAPERS, 7 ROBOTS PATROL THE STREETS WHILE 32 PEOPLE RIDE BIKES AND 18 CARS ZOOM BY, CREATING A BALANCED CHAOS UNDER THE BRILLIANT SUNLIGHT REFLECTING OFF GLASS AND METAL",
                "A STRONG WIND BLEW ACROSS 88 HILLS AS 12 HIKERS CLIMBED UP AND 45 BIRDS SOARED HIGH, 7 CAMERAS CAPTURED EVERY MOVEMENT, WHILE 99 TREES SWAYED IN A RHYTHMIC DANCE UNDER A CLEAR BLUE SKY WITH 5 SCATTERED CLOUDS",
                "DURING THE 31ST ANNUAL FESTIVAL, 6 BANDS PLAYED 42 SONGS AS 99 DANCERS PERFORMED, 12 FOOD STALLS SERVED 88 TYPES OF SNACKS, AND 17 FIREWORKS BURST IN THE SKY, MAKING 2026 A MEMORABLE YEAR FOR EVERY VISITOR",
                "ON A QUIET NIGHT, 14 CATS ROAMED 27 STREETS WHILE 3 DOGS SLEPT, 42 STREETLAMPS GLOWED SOFTLY, AND 99 STARS SHONE BRIGHTLY, AS 7 HUMANS WALKED SILENTLY, ENJOYING THE PEACEFUL ATMOSPHERE OF THE CITY",
                "THE MYSTERIOUS CASTLE STOOD ON 77 HILLS, 12 KNIGHTS PATROLLED THE WALLS, 5 DRAGONS FLEW ABOVE, AND 88 FLAGS WAVED IN THE WIND, WHILE 33 TORCHES ILLUMINATED THE PATHS FOR 20 VISITORS WHO DARED TO EXPLORE",
                "IN THE LARGE LIBRARY, 99 BOOKS WERE ARRANGED ON 42 SHELVES, 17 SCHOLARS STUDIED DILIGENTLY, 5 COMPUTERS WERE IN USE, AND 12 LAMPS CAST A WARM LIGHT, WHILE 8 CLOCKS TICKED IN PERFECT HARMONY THROUGH THE HALLS",
                "A HIGHWAY STRETCHED ACROSS 88 MILES, 12 TRUCKS RUMBLED ALONG, 37 CARS SPEEDILY PASSED, 6 BICYCLES WEAVED CAREFULLY, AND 99 SIGNS INSTRUCTED DRIVERS, AS 7 DRONES FILMED THE SCENE FROM ABOVE UNDER A SUNNY SKY",
                "THE SPACE STATION ORBITED 42 MILES ABOVE EARTH, 7 ASTRONAUTS PERFORMED 33 EXPERIMENTS, 5 ROBOTS ASSISTED, AND 88 LIGHTS ILLUMINATED THE MODULES, AS 12 SATELLITES PASSED BY, MAKING 2026 A YEAR OF DISCOVERY",
                "ON THE DESERT PLAIN, 77 CAMELS WALKED IN A LINE, 12 NOMADS FOLLOWED BEHIND, 5 OASES SPARKLED IN THE DISTANCE, AND 99 SAND DUNES SHIFTED WITH THE WIND, AS 7 SUNS SETTING CREATED A MESMERIZING ORANGE HUE",
                "THE TECH CONFERENCE HOSTED 42 SPEAKERS, 12 PANELS DISCUSSED AI, 5 ROBOTS GAVE DEMOS, 88 COMPANIES EXHIBITED PRODUCTS, AND 99 ATTENDEES NETWORKED, MAKING 2026 A LANDMARK YEAR FOR INNOVATION AND TECHNOLOGY",
                "IN THE GRAND THEATER, 99 ACTORS PERFORMED ON 42 STAGES, 17 ORCHESTRAS PLAYED MUSIC, 6 LIGHTS ILLUMINATED THE SCENES, AND 88 AUDIENCE MEMBERS APPLAUDED, CREATING A MAGICAL EVENING FULL OF ART AND CULTURE",
                "A LARGE GARDEN SPREAD ACROSS 88 ACRES, 12 FOUNTAINS SPRANG WATER, 7 STATUES STOOD MAJESTIC, 42 FLOWERS BLOOMED, AND 99 BUTTERFLIES FLUTTERED, WHILE 5 GARDENERS TENDED TO THE BEAUTY OF THE LANDSCAPE",
                "ON THE ICE FIELD, 33 HOCKEY PLAYERS RAN, 12 PUCKS SLID QUICKLY, 5 GOALIES DEFENDED, 88 SPECTATORS CHEERED, AND 7 LIGHTS SPARKLED, MAKING A NIGHT OF SPORT AND EXCITEMENT UNDER THE COOL GLOW OF 99 STARS",
                "DURING THE SPACE EXHIBITION, 42 ROCKETS WERE DISPLAYED, 7 MODELS LAUNCHED, 88 VISITORS WATCHED, 12 SCIENTISTS EXPLAINED, AND 5 DRONES FILMED THE EVENT, CREATING A FUTURISTIC AND COHESIVE EXPERIENCE FULL OF WONDER"
        );

        int count = 0;
       for(AbstractCipher cipher : cipherAlgorithsMap.values()){
           String sentence = sentences.get(count);
           sentence = sentence.replaceAll("[^A-Z0-9]", "");
           ciphertextSamples.put(cipher.name(), cipher.encrypt(sentence, cipher.generateRandomKey()));
           count++;
       }

       for(Map.Entry<String, String> entry : ciphertextSamples.entrySet()){
           System.out.println(entry.getKey() + "," + entry.getValue());
       }
    }
}
